# Generated by Django 4.0.6 on 2022-08-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagepost'),
        ),
    ]
