# Generated by Django 4.0.6 on 2022-08-19 01:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_posteos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
