# Generated by Django 4.0.6 on 2022-08-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuario',
            name='description',
            field=models.CharField(default='description test', max_length=50),
            preserve_default=False,
        ),
    ]
